[POWEREVIEW-2] create order in power reviews
vtex-apps/powerreviews pull request #89
Opened 2022-06-29 16:02 UTC by whc105

**What problem is this solving?**

Sends an email (after a day, or whatever the given interval is) when orders are invoiced

**How should this be manually tested?**

Place an order. Invoice it. Wait a day

2022-07-14 18:55 UTC, Arturo777 requested changes

2022-07-14 18:55 UTC, Arturo777 commented on node/middlewares/invoiced.ts
> +    clients: { license, oms, powerreviews },
```suggestion
    clients: { license, oms, powerreviews },
    vtex: { logger },
```

2022-07-14 18:55 UTC, Arturo777 commented on node/middlewares/invoiced.ts
> +    const order: any = await oms.getOrder(orderId)
```suggestion
    const order: any = await oms.getOrder(orderId).catch((error) => {
      logger.error({
        message: 'invoiced-oms-getOrder-error',
        error,
      })
    })
```

2022-07-14 18:55 UTC, Arturo777 commented on node/middlewares/invoiced.ts
> +    const userEmail: any = await license.getUser(
```suggestion
const userEmail: any = await license
      .getUser(order?.clientProfileData?.userProfileId)
      .catch((error) => {
        logger.error({
          message: 'invoiced-license-getUser-error',
          error,
        })
      })
```

2022-07-14 18:55 UTC, Arturo777 commented on node/middlewares/invoiced.ts
> +    await powerreviews.createOrder(orderInfo, encoding)
```suggestion
    await powerreviews.createOrder(orderInfo, encoding).catch((error) => {
      logger.error({
        message: 'powerreviews-createOrder-error',
        error,
      })
    })
```

2022-07-15 18:18 UTC, polishq approved these changes
LGTM

2022-07-15 18:41 UTC, Arturo777 approved these changes
LGTM

2022-07-15 18:55 UTC, sheilagomes approved these changes

2022-07-15 18:56 UTC, merged